name: "Aurora Migration"
on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: "Deployment target"
        required: true
        default: "BETA_DEVELOPMENT"
        type: choice
        options:
          - DEVELOPMENT
          - PRODUCTION
          - STAGE
          - BETA_PRODUCTION
          - BETA_DEVELOPMENT
          - BETA_STAGING
jobs:
  db-deploy:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    environment: ${{ inputs.deployment_target }}
    steps:
      - name: DB Migration
        uses: actions/github-script@v6
        with:
          script: |
            console.log(`Deployment target: ${{ inputs.deployment_target }}`);
            await new Promise(resolve => setTimeout(resolve, 5000));
